name: PHP workflow for Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: :opcache, xdebug
          tools: composer, php-cs, phpunit
          coverage: xdebug

      - name: Report PHP version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: composer install
        working-directory: ${{env.working-directory}}

      - name: Lint project .php files
        run: ./vendor/bin/phpcs .
        working-directory: ${{env.working-directory}}

      - name: Run tests and generate coverage report
        env:
          XDEBUG_MODE: coverage
        run: ./vendor/bin/codecept run
        working-directory: ${{env.working-directory}}