version: "3.8"

services:

  app:
    container_name: "app-${PROJECT_NAME}"
    build: ../php
    restart: unless-stopped
    depends_on:
      - "composer_installation"
      - "mysql"
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ../../src:/www/
    env_file: ../../.env
    entrypoint: "php yii serve 0.0.0.0:8080"

  composer_installation:
    container_name: "composer-${PROJECT_NAME}"
    image: composer
    volumes:
      - ../../src:/www/
    working_dir: /www
    command: "composer install"

  mysql:
    container_name: "mysql-${PROJECT_NAME}"
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"

  phpmyadmin:
    container_name: "phpmyadmin-${PROJECT_NAME}"
    image: phpmyadmin:5.1.0
    restart: unless-stopped
    depends_on:
      - "mysql"
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: "1"
      PMA_USER: "root"
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: "mysql-${PROJECT_NAME}"
